#!/usr/bin/env python3
"""Bike glyph for the badge, frozen as a 1-bit bitmap.

The icon is drawn here (midpoint circles + Bresenham lines) and exported two
ways from the same pixel grid: `ICON` rows for preview.py, and a GFX-style
PROGMEM bitmap (MSB-first, byte-aligned rows) written to
bike_display/bike_icon.h for canvas.drawBitmap(). Both renderers therefore
show identical pixels. Re-run this script after changing the drawing.
"""

from pathlib import Path

ICON_W, ICON_H = 48, 30


def _circle(px, cx, cy, r):
    """Midpoint circle outline."""
    x, y, d = r, 0, 1 - r
    while x >= y:
        for dx, dy in ((x, y), (y, x), (-y, x), (-x, y),
                       (-x, -y), (-y, -x), (y, -x), (x, -y)):
            px.add((cx + dx, cy + dy))
        y += 1
        if d < 0:
            d += 2 * y + 1
        else:
            x -= 1
            d += 2 * (y - x) + 1


def _line(px, x0, y0, x1, y1):
    """Bresenham line."""
    dx, dy = abs(x1 - x0), -abs(y1 - y0)
    sx, sy = (1 if x0 < x1 else -1), (1 if y0 < y1 else -1)
    err = dx + dy
    while True:
        px.add((x0, y0))
        if x0 == x1 and y0 == y1:
            return
        e2 = 2 * err
        if e2 >= dy:
            err += dy
            x0 += sx
        if e2 <= dx:
            err += dx
            y0 += sy


def _thick_line(px, x0, y0, x1, y1):
    """2px-thick line: draw twice, offset perpendicular-ish."""
    _line(px, x0, y0, x1, y1)
    if abs(x1 - x0) >= abs(y1 - y0):
        _line(px, x0, y0 + 1, x1, y1 + 1)
    else:
        _line(px, x0 + 1, y0, x1 + 1, y1)


def build_icon():
    px = set()
    # Wheels: 2px-thick outlines
    for r in (8, 7):
        _circle(px, 10, 20, r)
        _circle(px, 38, 20, r)
    # Frame (diamond): seat cluster S, crank B, head tube Hd
    S, B, Hd = (17, 6), (24, 20), (33, 8)
    _thick_line(px, 10, 20, *B)     # chainstay: rear hub -> crank
    _thick_line(px, 10, 20, *S)     # seat stay: rear hub -> seat cluster
    _thick_line(px, *S, *Hd)        # top tube
    _thick_line(px, *Hd, *B)        # down tube
    _thick_line(px, *S, 16, 3)      # seat post
    _thick_line(px, 38, 20, *Hd)    # fork
    _thick_line(px, *Hd, 35, 3)     # stem
    _line(px, 12, 2, 20, 2)         # seat
    _line(px, 12, 3, 20, 3)
    _line(px, 33, 2, 39, 2)         # handlebar
    _line(px, 33, 3, 39, 3)

    rows = [[1 if (x, y) in px else 0 for x in range(ICON_W)]
            for y in range(ICON_H)]
    return rows


ICON = build_icon()


def emit_header(path):
    stride = (ICON_W + 7) // 8
    data = []
    for row in ICON:
        for b in range(stride):
            byte = 0
            for bit in range(8):
                x = b * 8 + bit
                if x < ICON_W and row[x]:
                    byte |= 0x80 >> bit
            data.append(byte)
    lines = [
        "// Generated by preview/bike_icon.py - do not edit by hand",
        "#pragma once",
        "#include <pgmspace.h>",
        f"#define BIKE_ICON_W {ICON_W}",
        f"#define BIKE_ICON_H {ICON_H}",
        "static const uint8_t BIKE_ICON[] PROGMEM = {",
    ]
    for i in range(0, len(data), 12):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 12]) + ",")
    lines += ["};", ""]
    path.write_text("\n".join(lines))
    print(f"wrote {path}")


if __name__ == "__main__":
    emit_header(Path(__file__).parent.parent / "bike_display" / "bike_icon.h")
